### ISSUE TITLE
Analyze expenses

### ISSUE THREAD

**Issue by Diez3** [Diez3/GESPRO_Practica_2_Curso_2024_2025#16]

**Comment by Diez3** [comment]
Buenas, ¿necesitas ayuda?

**Comment by lorcel23** [comment]
De momento no, únicamente consultar la fecha de entrega del release al que pertenece

**Comment by Diez3** [comment]
Pertenece al release 1, siendo MVP, con fecha de entrega para el 05 de noviembre de 2024
