### ISSUE TITLE
Manage an app from an iPhone

### ISSUE THREAD

**Issue by Diez3** [Diez3/GESPRO_Practica_2_Curso_2024_2025#3]

**Comment by lorcel23** [comment]
Únicamente se podrá usar el app desde iPhone

**Comment by Diez3** [comment]
No, también se podrá usar en Android, aunque nos centraremos en ellos en Release 2 (7 de nov), no en MVP, más concretamente en la tarea "Manage an app from an Android device"

**Comment by lorcel23** [comment]
Vale, perfecto, me centro en brindarte ayuda en esta parte
