### ISSUE TITLE
Get account details

### ISSUE THREAD

**Issue by Diez3** [Diez3/GESPRO_Practica_2_Curso_2024_2025#6]

**Comment by Diez3** [comment]
Qué detalles de la cuenta vas a mostrar?

**Comment by lorcel23** [comment]
Voy a mostrar:
-número de cuenta
-NIF del cliente
-nombre y apellidos

**Comment by Diez3** [comment]
Perfecto,

Y el saldo actual de la cuenta?

**Comment by lorcel23** [comment]
Efectivamente, mostraré el saldo junto al interés anual aplicado a la cuenta

**Comment by Diez3** [comment]
Bien, si necesitas ayuda me dices
